spring.application.name=bff-cordillera
server.port=8084

# =============================================
# URLs de Microservicios
# =============================================
microservicio.datos.url=http://localhost:8083
microservicio.kpi.url=http://localhost:8082
microservicio.usuarios.url=http://localhost:8081

# =============================================
# Actuator
# =============================================
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always