spring.application.name=bff-cordillera
server.port=8084

# =============================================
# URLs de Microservicios
# =============================================
microservicio.datos.url=http://localhost:8083
microservicio.kpi.url=http://localhost:8082
microservicio.usuarios.url=http://localhost:8081

# =============================================
# Circuit Breaker - Resilience4j
# Si el 50% de llamadas falla en ventana de 10,
# el circuito se ABRE y retorna datos del cache
# =============================================
resilience4j.circuitbreaker.instances.ms-kpi.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.ms-kpi.slidingWindowSize=10
resilience4j.circuitbreaker.instances.ms-kpi.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.ms-kpi.failureRateThreshold=50
resilience4j.circuitbreaker.instances.ms-kpi.waitDurationInOpenState=5s
resilience4j.circuitbreaker.instances.ms-kpi.permittedNumberOfCallsInHalfOpenState=3

resilience4j.circuitbreaker.instances.ms-datos.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.ms-datos.slidingWindowSize=10
resilience4j.circuitbreaker.instances.ms-datos.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.ms-datos.failureRateThreshold=50
resilience4j.circuitbreaker.instances.ms-datos.waitDurationInOpenState=5s
resilience4j.circuitbreaker.instances.ms-datos.permittedNumberOfCallsInHalfOpenState=3

# =============================================
# Actuator
# =============================================
management.endpoints.web.exposure.include=health,info,circuitbreakers
management.endpoint.health.show-details=always